//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Student
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группа.
    /// </summary>
    // *** Start programmer edit section *** (Группа CustomAttributes)

    // *** End programmer edit section *** (Группа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппаE", new string[] {
            "Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("ГруппаE", "Студент", "СтудентE", true, "", "Студент", true, new string[] {
            ""})]
    [View("ГруппаL", new string[] {
            "Название as \'Название\'"})]
    public class Группа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private IIS.Student.DetailArrayOfСтудент fСтудент;
        
        // *** Start programmer edit section *** (Группа CustomMembers)

        // *** End programmer edit section *** (Группа CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Название CustomAttributes)

        // *** End programmer edit section *** (Группа.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Название Get start)

                // *** End programmer edit section *** (Группа.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Группа.Название Get end)

                // *** End programmer edit section *** (Группа.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Название Set start)

                // *** End programmer edit section *** (Группа.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Группа.Название Set end)

                // *** End programmer edit section *** (Группа.Название Set end)
            }
        }
        
        /// <summary>
        /// Группа.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Студент CustomAttributes)

        // *** End programmer edit section *** (Группа.Студент CustomAttributes)
        public virtual IIS.Student.DetailArrayOfСтудент Студент
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Студент Get start)

                // *** End programmer edit section *** (Группа.Студент Get start)
                if ((this.fСтудент == null))
                {
                    this.fСтудент = new IIS.Student.DetailArrayOfСтудент(this);
                }
                IIS.Student.DetailArrayOfСтудент result = this.fСтудент;
                // *** Start programmer edit section *** (Группа.Студент Get end)

                // *** End programmer edit section *** (Группа.Студент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Студент Set start)

                // *** End programmer edit section *** (Группа.Студент Set start)
                this.fСтудент = value;
                // *** Start programmer edit section *** (Группа.Студент Set end)

                // *** End programmer edit section *** (Группа.Студент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаE", typeof(IIS.Student.Группа));
                }
            }
            
            /// <summary>
            /// "ГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаL", typeof(IIS.Student.Группа));
                }
            }
        }
    }
}
