//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Student
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Студент.
    /// </summary>
    // *** Start programmer edit section *** (Студент CustomAttributes)

    // *** End programmer edit section *** (Студент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтудентE", new string[] {
            "Фамилия as \'Фамилия\'",
            "СреднийБалл as \'Средний балл\'"})]
    public class Студент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private double fСреднийБалл;
        
        private IIS.Student.Группа fГруппа;
        
        // *** Start programmer edit section *** (Студент CustomMembers)

        // *** End programmer edit section *** (Студент CustomMembers)

        
        /// <summary>
        /// СреднийБалл.
        /// </summary>
        // *** Start programmer edit section *** (Студент.СреднийБалл CustomAttributes)

        // *** End programmer edit section *** (Студент.СреднийБалл CustomAttributes)
        public virtual double СреднийБалл
        {
            get
            {
                // *** Start programmer edit section *** (Студент.СреднийБалл Get start)

                // *** End programmer edit section *** (Студент.СреднийБалл Get start)
                double result = this.fСреднийБалл;
                // *** Start programmer edit section *** (Студент.СреднийБалл Get end)

                // *** End programmer edit section *** (Студент.СреднийБалл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.СреднийБалл Set start)

                // *** End programmer edit section *** (Студент.СреднийБалл Set start)
                this.fСреднийБалл = value;
                // *** Start programmer edit section *** (Студент.СреднийБалл Set end)

                // *** End programmer edit section *** (Студент.СреднийБалл Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Студент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Фамилия Get start)

                // *** End programmer edit section *** (Студент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Студент.Фамилия Get end)

                // *** End programmer edit section *** (Студент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Фамилия Set start)

                // *** End programmer edit section *** (Студент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Студент.Фамилия Set end)

                // *** End programmer edit section *** (Студент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Student.Группа.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Группа CustomAttributes)

        // *** End programmer edit section *** (Студент.Группа CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Группа"})]
        public virtual IIS.Student.Группа Группа
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Группа Get start)

                // *** End programmer edit section *** (Студент.Группа Get start)
                IIS.Student.Группа result = this.fГруппа;
                // *** Start programmer edit section *** (Студент.Группа Get end)

                // *** End programmer edit section *** (Студент.Группа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Группа Set start)

                // *** End programmer edit section *** (Студент.Группа Set start)
                this.fГруппа = value;
                // *** Start programmer edit section *** (Студент.Группа Set end)

                // *** End programmer edit section *** (Студент.Группа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтудентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентE", typeof(IIS.Student.Студент));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Студент.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтудент CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтудент CustomAttributes)
    public class DetailArrayOfСтудент : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Student.DetailArrayOfСтудент members)

        // *** End programmer edit section *** (IIS.Student.DetailArrayOfСтудент members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Студент by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Студент.
        /// </summary>
        public DetailArrayOfСтудент(IIS.Student.Группа fГруппа) : 
                base(typeof(Студент), ((ICSSoft.STORMNET.DataObject)(fГруппа)))
        {
        }
        
        public IIS.Student.Студент this[int index]
        {
            get
            {
                return ((IIS.Student.Студент)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Student.Студент dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
